<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Common.NuGet.Properties.xml" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Description>Membership algorithm implementation for a distributed .NET service</Description>
    <PackageTags>SlimCluster Cluster Membership Memberlist</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlimCluster\SlimCluster.csproj" />
  </ItemGroup>
 
</Project>
