version: 1.0.{build}
image: Visual Studio 2022
nuget:
  disable_publish_on_pr: true
build_script:
- ps: build\do_build.ps1
test_script:
- ps: build\do_test_ci.ps1
artifacts:
- path: dist\*.nupkg
  name: SlimCluster
deploy: off
notifications:
- provider: Email
  to:
  - maruszaktomasz@gmail.com
  subject: '[Build] SlimCluster'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
environment:
  azure_servicebus_key:
      secure: hsBLumILEW2YXIxS7gPLsLQMKBDPpHX2mRKE6NYps7VMKoVmoBDzeAyy+lEHjT3x
