apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-service
  labels:
    app: scca
spec:
  replicas: 3
  selector:
    matchLabels:
      run: sc-service
  template:
    metadata:
      labels:
        run: sc-service
    spec:
      containers:
      - name: sc-service
        image: zarusz/slimcluster_samples_service:latest
        imagePullPolicy: IfNotPresent # ensure we get always the fresh container image build
        ports:
        - containerPort: 5000
        - containerPort: 60001
