apiVersion: v1
kind: Service
metadata:
  name: sc-service-svc
  labels:
    run: sc-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: sc-service