<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Common.NuGet.Properties.xml" />

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Description>JSON serialization for SlimCluster</Description>
    <PackageTags>SlimCluster Cluster Serialization JSON</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlimCluster.Host\SlimCluster.Host.csproj" />
    <ProjectReference Include="..\SlimCluster.Serialization\SlimCluster.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
