# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "master", "release/*", "feature/*" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_NAME: SlimCluster.slnx
  SOLUTION_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: int-tests

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION_NAME
      working-directory: ./src
    - name: Build
      run: dotnet build $SOLUTION_NAME --configuration $SOLUTION_CONFIGURATION --no-restore
      working-directory: ./src
    - name: Test
      run: dotnet test $SOLUTION_NAME --configuration $SOLUTION_CONFIGURATION --no-build --verbosity normal --logger html --results-directory TestResults
      working-directory: ./src
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: ./src/TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}